return {
    products = {
        {
            name = 'weed_white-widow',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 1,
            minrep = 0,
        },
        {
            name = 'weed_skunk',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 2,
            minrep = 20,
        },
        {
            name = 'weed_purple-haze',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 3,
            minrep = 40,
        },
        {
            name = 'weed_og-kush',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 4,
            minrep = 60,
        },
        {
            name = 'weed_amnesia',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 5,
            minrep = 80,
        },
        {
            name = 'weed_white-widow_seed',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 6,
            minrep = 100,
        },
        {
            name = 'weed_skunk_seed',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 7,
            minrep = 120,
        },
        {
            name = 'weed_purple-haze_seed',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 8,
            minrep = 140,
        },
        {
            name = 'weed_og-kush_seed',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 9,
            minrep = 160,
        },
        {
            name = 'weed_amnesia_seed',
            price = 15,
            amount = 150,
            info = {},
            type = 'item',
            slot = 10,
            minrep = 180,
        },
    },
    cornerSellingDrugsList = {
        'weed_white-widow',
        'weed_skunk',
        'weed_purple-haze',
        'weed_og-kush',
        'weed_amnesia',
        'weed_ak47',
        'crack_baggy',
        'cokebaggy',
        'meth'
    },
    cornerSellingDrugsPrice = {
        ['weed_white-widow'] = {
            min = 15,
            max = 24,
        },
        ['weed_og-kush'] = {
            min = 15,
            max = 28,
        },
        ['weed_skunk'] = {
            min = 15,
            max = 31,
        },
        ['weed_amnesia'] = {
            min = 18,
            max = 34,
        },
        ['weed_purple-haze'] = {
            min = 18,
            max = 37,
        },
        ['weed_ak47'] = {
            min = 18,
            max = 40,
        },
        ['crack_baggy'] = {
            min = 18,
            max = 34,
        },
        ['cokebaggy'] = {
            min = 18,
            max = 37,
        },
        ['meth'] = {
            min = 18,
            max = 40,
        },
    },
    scamChance = 25,
    policeCallChance = 15,
    useMarkedBills = false,
    deliveryRepGain = 1,
    deliveryRepLoss = 1,
    policeDeliveryModifier = 2,
    wrongAmountFee = 2,
    overdueDeliveryFee = 4
}